# Generated by Django 5.2.5 on 2025-09-03 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('user_from', models.F('user_to')), _negated=True), name='prevent_self_follow'),
        ),
    ]
