# Generated by Django 6.0.7 on 2026-08-05 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact_prevent_self_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_user_follow'),
        ),
    ]
