# Generated by Django 6.0.7 on 2026-08-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_total_likes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_total_l_0bcd7e_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='total_likes',
        ),
    ]
