# Generated by Django 6.0.7 on 2026-08-05 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_images_imag_total_l_0bcd7e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='image',
            new_name='image_created_idx',
            old_name='images_imag_created_d57897_idx',
        ),
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-total_likes'], name='image_likes_idx'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(condition=models.Q(('total_likes__gte', 0)), name='image_total_likes_gte_0'),
        ),
    ]
